project:
  type: website

website:
  favicon: assets/favicon.png
  # google-analytics: G-CES9J82GLL
  page-footer: 
    center:
      - text: Home / About / License
        href: index.qmd
      - text: GitHub
        href: "https://github.com/61c-teach/course-notes"
      - text: Accessibility
        href: "https://dap.berkeley.edu/get-help/report-web-accessibility-issue"
      - text: Nondiscrimination
        href: "https://ophd.berkeley.edu/policies-and-procedures/nondiscrimination-policy-statement"
    background: "dark"
  page-navigation: true
  sidebar:
    style: "docked"
    title: "CS 61C <br><small>Course Notes</small>"
    logo: assets/favicon.png
    logo-alt: "CS61C Logo"
    collapse-level: 1 # doesn't expand next level
    tools:
      - icon: github
        href: "https://github.com/61c-teach/course-notes"
    contents:
      - href: index.qmd
        text: Home / About
      - section: Number Representation
        href: content/number_rep/index.qmd
        contents:
          - href: content/number_rep/index.qmd
            text: Number Representation
          - href: content/number_rep/unsigned.qmd
            text: Unsigned Representations
          - href: content/number_rep/signed.qmd
            text: Signed Representations
      - section: RISC-V
        href: content/RISC-V/index.qmd
        contents:
          - href: content/RISC-V/instruction_formats.qmd
            text: RISC-V Instruction Formats

format:
  html:
    theme: lumen
    fontsize: 1em
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html

