project:
  type: website

website:
  favicon: assets/favicon.png
  # google-analytics: G-CES9J82GLL
  page-footer: 
    center:
      - text: Home / About / License
        href: index.qmd
      - text: GitHub
        href: "https://github.com/61c-teach/course-notes"
      - text: Accessibility
        href: "https://dap.berkeley.edu/get-help/report-web-accessibility-issue"
      - text: Nondiscrimination
        href: "https://ophd.berkeley.edu/policies-and-procedures/nondiscrimination-policy-statement"
    background: "dark"
  page-navigation: true
  sidebar:
    style: "docked"
    title: "CS 61C <br><small>Course Notes</small>"
    logo: assets/favicon.png
    logo-alt: "CS61C Logo"
    collapse-level: 1 # doesn't expand next level
    tools:
      - icon: github
        href: "https://github.com/61c-teach/course-notes"
    contents:
      - href: index.qmd
        text: Home / About
      - section: Number Representation
        href: content/number-rep/index.qmd
        contents:
          - href: content/number-rep/index.qmd
            text: Introduction
          - href: content/number-rep/binary-decimal-hex.qmd
            text: "Binary, Decimal, Hex"
          - href: content/number-rep/integer-representations.qmd
            text: "Integer Representations"
          - href: content/number-rep/simple-reps.qmd
            text: "Sign-Magnitude, Onesâ€™ Complement"
          - href: content/number-rep/twos-complement.qmd
            text: "Two's Complement"
          - href: content/number-rep/bias-encoding.qmd
            text: "Bias Encoding"
          - href: content/number-rep/summary.qmd
            text: "Summary"
          - href: content/number-rep/exercises.qmd
            text: "General Exercises"
          - href: content/number-rep/precheck-unsigned.qmd
            text: "Unsigned Representations"
          - href: content/number-rep/precheck-unsigned.qmd
            text: "Signed Representations"

format:
  html:
    theme: lumen
    fontsize: 1em
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html

